### ISSUE TITLE
[ERROR]: __str__ returned non-string (type Error)

### ISSUE THREAD

**Issue by saeedsurat** [unioslo/zabbix-cli#133] opened 2020-12-03 23:59 UTC
Getting below error after entering username and password

[ERROR]: __str__ returned non-string (type Error)

**Comment by paalbra** [comment] 2021-09-30 15:11
This is hard to debug without knowing the zabbix-cli or zabbix version. I'm going to close it now, but please reopen with more details if the issue is still present! :+1:

**Closed by paalbra** 2021-09-30 15:11 UTC
